### ISSUE TITLE
Add: `Repeater` field Component

### ISSUE THREAD

**Issue by fabiankaegy** [10up/block-components#108]
Repeater fields are a common pattern we see when working with blocks. A component to make it easier to work with would be great.

**Comment by fabiankaegy** [comment]
The idea here is to build this as a react component that uses render props for it's children. So the API when using this component looks something like this: 

```jsx
export function BlockEdit(props) {
    const { attributes, setAttributes } = props;
    const { items } = attributes;

    return (
        <Repeater attribute="items">
            {( item, setItem, removeItem ) => (
                <TextControl value={item} onChange={setItem} />
            )}
        </Repeater>
    );
}
```

The `Repeater` component takes care of managing the data in the attributes ideally via the data API ([`updateBlockAttributes`](https://github.com/WordPress/gutenberg/blob/6fcd3c88a4bc694ce9866e2375dcc5eb0908c85d/docs/reference-guides/data/data-core-block-editor.md#updateblockattributes), etc.) so that you don't manually have to pass in the value of the attribute and the `setAttributes` handler. 

The type definition of the attribute needs to be set as `array`

Additionally, the `Repeater` component should allow developers to replace the appended button used to add new items to it. Maybe an API similar to how the `InnerBlocks` component accepts the `renderAppender` prop and also exports the default render appended as a react component to be used in your own custom implementations.

**Comment by Sidsector9** [comment]
@fabiankaegy can a repeater field be a group field? For example a group field containing a TextControl and a ToggleControl? If so, how should setItem work in this scenario?

**Comment by fabiankaegy** [comment]
@Sidsector9 Yes very much so :) developers should be able to place anything (except for inner blocks) into repeater fields. 

I imagine setItem to work similarly to how setAttributes works itself. The value of each item can either be a singular value like a string or number or it can also be an object or an array. And so the set item function can be used to update that object for example which would then feed the individual components within the repeater field.

**Comment by Sidsector9** [comment]
@fabiankaegy I found this challenging and it'd be great to hear your thoughts.

Consider this scenario where a Repeater item has a TextControl and ToggleControl as a group and the corresponding default attribute is of the form:

```
attributes: {
    repeaterData: {
        type: 'array',
        default: [
            {
                textControlVal: '',
                toggleControlVal: false,
            }
        ]
    }
}
```

Let say when a user updates ToggleControl, how can I determine which field was updated and which property under the attributes.repeaterData[index] needs to be updated from within `setItem`?

**Comment by fabiankaegy** [comment]
@Sidsector9 The way I'm thinking about this is, that `setItem` replicates the functionality of `setAttributes` but works for a specific item in the array. 

So the index will always be inherited from the `map` and that is how you can target the item. 

From there I think we could make it so that the `setItem` function can either accept a `string` or `number` and then just set that value. This would be used for singular values. However, if you pass an `object` to the `setItem` function it sets the keys you provide in that object for the new attributes.

So for example, if we have this attribute structure:

```js
attributes: {
    items: [
        {
            textControlVal: '',
            toggleControlVal: false,
        }
    ]
}
```

and you call `setItem` like so: 

```js 
setItem({ textControlVal: 'Hello World' }) 
```

The resulting attributes would look like this:

```js
attributes: {
    items: [
        {
            textControlVal: 'Hello World',
            toggleControlVal: false,
        }
    ]
}
```


If on the other hand, the items are not objects but raw strings you can do the following:

```js
attributes: {
    items: [
        'Hello World'
    ]
}
```

```js
setItem( "Testing" );
```

the result would be

```js
attributes: {
    items: [
        'Testing'
    ]
}
```


And the index always comes from the map and therefore you know which string or which object to change. 

(I might be missing something in this explanation so do let me know if that is not possible or there are any issues :))

**Comment by Sidsector9** [comment]
@fabiankaegy your examples gave more clarity. I've made small changes to support grouped fields here - [0a99bd4](https://github.com/10up/block-components/pull/110/commits/0a99bd41666d48a9a76aa797600c801fa2469117)
