### ISSUE TITLE
Provide unminified source

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/block-components#121]
### Is your enhancement related to a problem? Please describe.

I _think_ we should provide unminified sources for the package when is published. This would help to debug when developing.

Given that React always goes through some bundling pipeline, I think there's no harm in offering this but wanted to check other opinions first.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@Antonio-Laguna Do you have any pointers for me on how we could go about this? I would also like to ship better source maps in general to get more relevant console errors / debugger output when working on integrating these components.
