### ISSUE TITLE
Link: After setting a link URL, there's currently no way to clear out the link URL value

### ISSUE THREAD

**Issue by roseg43** [10up/block-components#138]
### Describe the bug

When working with the `Link` component, there is no way to unset the `linkUrl` using the component. I either expect a button that allows an editor to unset the URL value, or allow for an empty string to be passed to the URL input.

### Steps to Reproduce

1. Go to a edit page and insert a block that uses the `Link` component
2. Set a URL on the `Link` component
3. Attempt to unset the URL on the `Link` component

### Screenshots, screen recording, code snippet

Video of the issue in action: 
https://user-images.githubusercontent.com/7225212/186250812-902fbd75-5795-4d65-9d37-95fe9f3af2da.mov

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
That is a great observation. I agree we should add the ability to clear a link 👍
