### ISSUE TITLE
Image: UI for replacing/removing an image after an image has been selected is missing

### ISSUE THREAD

**Issue by roseg43** [10up/block-components#139]
### Describe the bug

The demo GIF on the [Image component readme](https://github.com/10up/block-components/tree/develop/components/image) shows a toolbar UI for adding, removing, and replacing images. However, it would appear this is missing in the current version of the component.

After adding an image, I expect to be able to remove or update the image.

In actuality, adding an image replaces the `MediaPlaceholder` with an `<img>` element that has no controls, and no additional controls are rendered in the block toolbar.

### Steps to Reproduce

1. Add this component to a block
2. Upload/select an image for the block using the Image component
3. Attempt to change/remove the image after an image has been selected

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@roseg43 chrrently this functionality is divided into the separate MediaToolbar component. But I've long thought that we should likely combine the two. We just need to find a backwards compatible way to introduce this  

For now I'd recommend adding the MediaToolbar component manually to the BlockControls slot of your block.

**Comment by roseg43** [comment]
@fabiankaegy I thought I was missing something! In that case, do you see there being value in adding some info to the readme that mentions this? As currently without adding `MediaToolbar` you can't actually remove/replace an image once you pick one? Happy to submit a PR for this, by the way 😄

**Comment by fabiankaegy** [comment]
@roseg43 id love to see a pr for that :)

and if you have ideas how we could add it to the image component itself whilst keeping backwards compatibility intact do let me know :)

**Comment by fabiankaegy** [comment]
The docs were updated in 52c7ff72794947fb72a25acc3f541b0bfb5ce293
