### ISSUE TITLE
Content Picker: at narrow widths, too little of the post title is visible

### ISSUE THREAD

**Issue by johnwatkins0** [10up/block-components#17]
**Is your enhancement related to a problem? Please describe.**

When using the content picker within narrow containers such as the block editor sidebar, it can be difficult to find the post you're looking for because the titles are cut off after the first couple of words. Screenshot:

<img width="276" alt="Screen Shot 2021-03-16 at 4 56 56 PM" src="https://user-images.githubusercontent.com/9020968/111385441-d0127480-8678-11eb-9709-571d5b799090.png">

**Describe the solution you'd like**

I know the CSS can be overridden within my project to make more of the title show (it's currently hidden with CSS), but by default within the component I suggest we surface the title either as a browser-native title attribute (see below) or with a similar Gutenberg component.

<img width="295" alt="Screen Shot 2021-03-16 at 4 59 42 PM" src="https://user-images.githubusercontent.com/9020968/111385720-37302900-8679-11eb-83c5-c281463f86ba.png">

Additionally, we might revisit the "post" badge shown to the right of the button, particularly when we are searching only one post type, in which scenario it adds no meaningful information.

**Comment by xavortm** [comment]
Added the hover tooltip in the PR here - https://github.com/10up/block-components/pull/60

To be honest, I think that we can also have the prop to "show full titles"? It would be up to the developer to decide what works for them.
