### ISSUE TITLE
Content Picker search can run less often

### ISSUE THREAD

**Issue by johnwatkins0** [10up/block-components#18]
**Is your enhancement related to a problem? Please describe.**
The search runs every time input changes. While this is generally not a problem, it can be an issue on slow connections, and it is technically possible to type so fast that you reach the limit of the simultaneous requests the browser will allow.

**Describe the solution you'd like**

No need to debounce. Instead, we can just make sure only one fetch request is running at a time. After a fetch completes, we check whether the search term has changed; if it has, search again. This way we will still make a lot of requests that are never surfaced in the UI as the user types, but it will be fewer requests than what the component does now.

**Designs**

**Describe alternatives you've considered**

Debouncing, though as described above, I don't think it's necessary.

**Additional context**

I'll send a PR for this, unless someone else sees this and wants to try it.

**Comment by xavortm** [comment]
Also probably fixed in #71

**Comment by fabiankaegy** [comment]
Closing this as it appears to be fixed as of #71
