### ISSUE TITLE
Image component Focal Picker needs default settings

### ISSUE THREAD

**Issue by colinswinney** [10up/block-components#182]
### Describe the bug

For the Image component, if you wish to use the Focal Picker, you must declare default values in your block.json attributes for it to render. 

cc: @ncoetzer 

### Steps to Reproduce

1. Add component as outlined in the [readme](https://github.com/10up/block-components/blob/develop/components/image/readme.md)
2. Add your attributes to block.json
```
{
  ...
  "attributes": {
    "imageId": {
      "type": "number"
    },
    "focalPoint": {
      "type": "object"
    }
  }
}
```
See that the Focal Picker doesn't render.  

### Screenshots, screen recording, code snippet

Proposed solution would be to outline in the readme file that default settings must be added for it to render.  

```
{
  ...
  "attributes": {
    "imageId": {
      "type": "number"
    },
    "focalPoint": {
      "type": "object",
      "default": {
        "x": 0.5,
        "y": 0.5
      }
    }
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@colinswinney Thanks for reporting this issue :)
