### ISSUE TITLE
ContentPicker: start wrapper CSS class with a letter instead of a number

### ISSUE THREAD

**Issue by johnwatkins0** [10up/block-components#20]
**Is your enhancement related to a problem? Please describe.**

https://github.com/10up/block-components/blob/da265f392270ea56a6329506dfbf507b44f4c4a7/components/ContentPicker/index.js#L104

When rendered, this produces

```HTML
<div class="10up-content-picker">
    ....
</div>
```

While it is possible to select that CSS class, it is more difficult than if the class were `tenup-content-picker`

**Describe the solution you'd like**

The class should be `tenup-content-picker`.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by fabiankaegy** [comment]
This was resolved as part of https://github.com/10up/block-components/pull/71
