### ISSUE TITLE
Feature request: Post meta box components

### ISSUE THREAD

**Issue by johnwatkins0** [10up/block-components#208]
### Is your enhancement related to a problem? Please describe.

Proposing a pair of components that would make it easier to add post meta boxes to the block editor. This would replace custom ad hoc solutions for projects or reliance on PHP-based plugins like FieldManager whose UI doesn't match the modern editor.

I don't think something like this already exists in core or this library, but let me know if I've missed something.

The two components I have in mind would be `PostMetaGroup` and `PostMetaField`, and they would work something like this:

```JS
const MyComponent = () => {
	return (
		<InspectorControls>
			<PostMetaGroup
				title="My Group"
				description="My Group Description"
				location="side"
			>
				<PostMetaField
					title="My Field"
					description="My Field Description"
					help="My Field Help"
					field="my_field"
					type="string"
				/>
				<PostMetaField
					title="Start Date"
					description="Start Date Description"
					help="Start Date Help"
					field="start_date"
					type="date"
				/>
				<PostMetaField
					title="Link"
					description="Link Description"
					help="Link Help"
					field="link"
					type="url"
				/>
			</PostMetaGroup>
		</InspectorControls>
	)
};
```

The `PostMetaGroup` would create a panel in the sidebar with the specified title and description, and the panel would contain panel rows for each of the `PostMetaField` components. The PostMetaField components would use the `type` prop (and maybe additional props would be needed for certain scenarios -- e.g., to support conditional logic) to determine which UI to show. All would rely on core Gutenberg components for the UI.

The `PostMetaField` component would also internally handle editing the field in the editor data store (so the meta value doesn't need to be passed in).

Separately, the meta fields would need to be registered in PHP with `register_post_meta` and the `show_in_rest` argument defined as true or setting the schema.

As an alternative approach (both could be supported), the `PostMetaGroup` component could accept a `fields` property.

```JS
const MyComponent = () => {
	return (
		<InspectorControls>
			<PostMetaGroup
				title="My Group"
				description="My Group Description"
				fields={[
					{
						title: 'My Field',
						description: 'My Field Description',
						help: 'My Field Help',
						fieldName: 'my_field',
						type: 'string',
					},
					{
						title: 'Start Date',
						description: 'Start Date Description',
						help: 'Start Date Help',
						fieldName: 'start_date',
						type: 'date',
					},
					{
						title: 'Link',
						description: 'Link Description',
						help: 'Link Help',
						fieldName: 'link',
						type: 'url',
					},
				]}
			/>
		</InspectorControls>
	)
};
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@johnwatkins0 The idea of the `<PostMetaGroup>` is really interresting. We just introduced a [`<PostMeta>`](https://github.com/10up/block-components/tree/develop/components/post-meta) component that already accomplished a lot of the things you are talking about here. However, that is currently mostly built for usage in the actual content inside a block. But you can pass it a render function if you want to customize the UI the component renders to make the meta value editable. 

I agree also that we need a lot more docs about all this. Let me know if you want to discuss this further :)

**Comment by johnwatkins0** [comment]
Thanks @fabiankaegy. I'll see if that PostMeta component does what I'm looking for and report back.

**Comment by johnwatkins0** [comment]
Closing, but may follow up later
