### ISSUE TITLE
Add Cypress as a dev dependency

### ISSUE THREAD

**Issue by asvinb** [10up/block-components#211]
### Is your enhancement related to a problem? Please describe.

I installed the `@10up/block-components` package and noticed that it took a while to install all the packages. After inspection, I found that it was due to Cypress being installed, which should not be the case for the packaged build.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
Thanks for the suggestion :) Fixed it in https://github.com/10up/block-components/commit/57af69c862012c89af7da19fa797f75be0ad0b8b and released a new patch version :)
