### ISSUE TITLE
Add support for multiple block into inner-block-slider component

### ISSUE THREAD

**Issue by mehidi258** [10up/block-components#224]
### Is your enhancement related to a problem? Please describe.

We are creating some slider, which have several variations and can have 3 custom block supports. But as of now i can see `inner-block-slider` component only accept single block as string in prop. So if we can support multiple block here that would be great. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
Thanks for this suggestion. For now I will close this issue as we have deprecated the `InnerBlockSlider` component
