### ISSUE TITLE
MediaToolbar component: Allow configuring labels

### ISSUE THREAD

**Issue by benlk** [10up/block-components#242]
### Is your enhancement related to a problem? Please describe.

Use case: I want to use the `MediaToolbar` with the `Video` component introduced in https://github.com/10up/block-components/pull/225, but the labels on this component assume that the bound media is an image: "Add Image", "Replace Image", "Remove Image".

https://github.com/10up/block-components/blob/6cec6c17b89abe9d19254f89b73f29ffd198a36d/components/media-toolbar/index.js#L28-L32

https://github.com/10up/block-components/blob/6cec6c17b89abe9d19254f89b73f29ffd198a36d/components/media-toolbar/index.js#L33-L37

https://github.com/10up/block-components/blob/6cec6c17b89abe9d19254f89b73f29ffd198a36d/components/media-toolbar/index.js#L44-L46

### Designs

Ideally, we'd be able to pass a `labels` argument to `MediaToolbar`, something like:

```js
<BlockControls>
	<MediaToolbar
		isOptional
		id={ video }
		onSelect={( media ) => setAttributes( {video: media.id} )}
		labels={{
			add: __( 'Add Video' ),
			replace: __( 'Replace Video' ),
			remove: __( 'Remove Video' )
		}}
	/>
</BlockControls>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Firestorm980** [comment]
@benlk @fabiankaegy WIP PR above that adds this feature.
