### ISSUE TITLE
Content Picker: show label even when max number of items is selected

### ISSUE THREAD

**Issue by johnwatkins0** [10up/block-components#25]
**Is your enhancement related to a problem? Please describe.**

Currently the label for the ContentPicker is passed down to the search input component, and the search input component is hidden when the max number of items has been selected. This can create a confusing UI where there is a list of posts with no heading, so it's not obvious what the list of posts is for.

<img width="259" alt="Screen Shot 2021-05-12 at 10 09 44 AM" src="https://user-images.githubusercontent.com/9020968/117999417-717d1600-b30a-11eb-8e35-cf4fd2e6f95c.png">

**Describe the solution you'd like**

The label passed into the content picker should always show. The label text can also be passed down to the input, but hidden.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sidsector9** [comment]
Hi @johnwatkins0,

I fixed the first part which says, "The label passed into the content picker should always show."

 However, I'm not clear about "The label text can also be passed down to the input, but hidden.". Can you please elaborate?
