### ISSUE TITLE
ContentPicker search results appear broken in WordPress 6.3

### ISSUE THREAD

**Issue by JakePT** [10up/block-components#260]
### Describe the bug

The search results in the `ContentPicker` component appear broken in WordPress 6.3.

They appear correct in WordPress 6.2. The main difference seems to be that in WordPress 6.3 the button element for each result is not receiving styles for the `.block-editor-link-control__search-item` selector, even though this class is still present.

### Steps to Reproduce

Using WordPress 6.2 with a ContentPicker component that has been implemented like this:

```js
<ContentPicker
	content={posts}
	contentTypes={['post']}
	isOrderable
	label={__('Posts')}
	maxContentItems={7}
	onPickChange={onChangePosts}
	placeholder={__('Search posts')}
/>
```

1. Perform a search for posts. The results should appear as expected.
2. Update to WordPress 6.3.1.
3. Perform the same search, the list will appear broken as shown below.

### Screenshots, screen recording, code snippet

<img width="279" alt="Screenshot 2023-08-31 at 3 17 49 pm" src="https://github.com/10up/block-components/assets/4100733/7042d936-5f4b-4312-af23-4d9f41fb1270">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
Hey @JakePT 👋 

Thanks for the report! We actually just fixed this in #252. So version `1.16.3` of the block components package should contain a fix for it. 

Let me know if you are still running into issues with that version. 

For now I will close this ticket :)
