### ISSUE TITLE
Repeater: Document shape of data in the attribute

### ISSUE THREAD

**Issue by benlk** [10up/block-components#261]
### Is your enhancement related to a problem? Please describe.

Took me a while to figure out what shape of data I needed to pass to the component.

The answer is: The data is an array of objects, with the property `id` reserved for the Repeater component.

```
[
  {
      "value": 241240,
      "id": "8fb96672-a48b-49c3-b837-017a465f3243"
  },
  ...
]
```

`setItem` must be passed an object, not the raw value. Here's what that looks like with an `Image`:

```
<Repeater
	attribute="beauty_artist_images"
	allowReordering={true}
	addButton={( addItem ) => ( <Button variant="primary" onClick={() => addItem()}>{__( 'Add Author Image' )}</Button> )}
	{ ...controlProps}
>
	{( item, index, setItem, removeItem ) => (
		<>
			<Image
				key={index}
				id={item.value}
				className=""
				size="thumbnail"
				onSelect={( image ) => setItem( {value: image.id} ) }
				multiple={false}
				labels={{
					title: __( 'Artist Image' ),
					instructions: __( 'Upload an image of the artist' )
				}}
			/>
			<Button isDestructive icon="trash" label={__( 'Remove' )} onClick={removeItem}/>
		</>
	)}
</Repeater>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@Sidsector9 Would you be able to take a stab at this? 

I know we've been running into a few problems with folks having issues getting this component to work the way they wanted to because the doc's weren't super clear.
