### ISSUE TITLE
CSS dependencies for repeater field?

### ISSUE THREAD

**Issue by jmplummer** [10up/block-components#277]
### Describe your question

Hey all,

I came across your repo when I was doing some searching to see if anyone had created an existing gutenberg repeater field. I've installed your package, and I have the repeater field _functioning_ correctly, but it does not appear to come with any styles or drag and drop functionality? Am I missing something? I've simply copied the example from the readme.md for that specific package and I did not see it importing anything other than `Repeater` from the components.

For clarity, this is what mine looks like out of the box:
![image](https://github.com/10up/block-components/assets/43279171/f2e4223b-d283-43c0-adff-e00af9a1ddb1)

Which obviously looks nothing like this:

![image](https://github.com/10up/block-components/assets/43279171/94eb79cc-e713-4084-99f0-b6b122347fbb)

TIA!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
Hey @jmplummer 👋 

I would recommend you take a look at the sample component here: https://github.com/10up/block-components/blob/develop/example/src/blocks/repeater-component-example/edit.js

The component primarily delivers the functionality. Not the styling
