### ISSUE TITLE
Repeater component drag and drop reordering is Broken in WordPress 6.4

### ISSUE THREAD

**Issue by fabiankaegy** [10up/block-components#278]
https://github.com/10up/block-components/assets/20684594/0656fbee-e3fe-4e1e-95c8-2a4e0ac141ff

Props: @ajmaurya99

**Comment by Sidsector9** [comment]
Initial investigation suggests the bug was introduced in [v1.17.0](https://github.com/10up/block-components/compare/v1.16.4...v1.17.0)
