### ISSUE TITLE
"Block validation failed" errors in console

### ISSUE THREAD

**Issue by Jorgu5** [10up/block-components#279]
### Describe the bug

When extending a block using your package, I am getting multiple block validation errors in developer console from default Wordpress blocks that occurs, while i'm trying to add a new block.

Here is my code extension

```import { registerBlockExtension } from '@10up/block-components';
import { InspectorControls } from '@wordpress/block-editor';
import { PanelBody, RangeControl, SelectControl } from '@wordpress/components';
// Define additional block attributes
const lineHeightAttribute = {
	lineHeight: {
		type: 'number',
		default: 1.5,
	},
	lineHeightUnit: {
		type: 'string',
		default: 'em',
	},
};

// Function to generate class names based on attributes
const classNameGenerator = ( attributes ) => {
	return `custom-line-height-${ attributes.lineHeight }`;
};

// Function to generate inline styles based on attributes
const inlineStyleGenerator = ( attributes ) => {
	return {
		lineHeight: `${ attributes.lineHeight }${ attributes.lineHeightUnit }`,
	};
};

// Custom Edit component
const CustomEditComponent = ( props ) => {
	const { attributes, setAttributes } = props;

	const unitOptions = [
		{ label: 'px', value: 'px' },
		{ label: 'em', value: 'em' },
	];

	const lineHeightControlProps =
		attributes.lineHeightUnit === 'px'
			? { min: 10, max: 100, step: 1 }
			: { min: 1, max: 3, step: 0.01 };

	return (
		<>
			<InspectorControls>
				<PanelBody title="Typography">
					<SelectControl
						label="Unit"
						value={ attributes.lineHeightUnit }
						options={ unitOptions }
						onChange={ ( value ) =>
							setAttributes( { lineHeightUnit: value } )
						}
					/>
					<RangeControl
						label="Line Height"
						value={ attributes.lineHeight }
						onChange={ ( value ) =>
							setAttributes( { lineHeight: Number( value ) } )
						}
						{ ...lineHeightControlProps }
					/>
				</PanelBody>
			</InspectorControls>
		</>
	);
};
// Register the block extension
registerBlockExtension( 'core/heading', {
	extensionName: 'custom-line-height',
	attributes: lineHeightAttribute,
	classNameGenerator,
	inlineStyleGenerator,
	Edit: CustomEditComponent,
	order: 'after',
} );
```

It looks like the save component is getting proper values, however the post body is not updated accordingly.

### Steps to Reproduce

1. Add the script into your blocks. 
2. Go to edit page / post.
3. Try to add a new block ( no matter which one).
4. Open developer console.
5. See errors. 

### Screenshots, screen recording, code snippet

<img width="1629" alt="image" src="https://github.com/10up/block-components/assets/18554836/5f0d6a61-125a-4b91-9968-fcb787c60bcb">

### Environment information

- Macbook M2 Pro
- Sonoma 14.1.1
- All browsers. 

### WordPress information

`
### wp-core ###

version: 6.4.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /blog/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 9
dotorg_communication: true

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Custom Theme
version: 1.0.0
author: Anonymous
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, block-templates, site-css, editor-style, automatic-feed-links, title-tag, post-thumbnails, menus, html5, customize-selective-refresh-widgets, custom-logo
auto_update: Disabled

### wp-themes-inactive (2) ###

Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.6, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

Local WP Live Link Helper: version: 2.0, author: Flywheel

### wp-plugins-active (8) ###

ACF Input Counter: version: 1.5, author: John A. Huebner II, Auto-updates disabled
Advanced Custom Fields PRO: version: 6.2.2, author: WP Engine (latest version: 6.2.4), Auto-updates disabled
Custom Blocks: version: 0.1.0, author: Custom, Auto-updates disabled
CookiePro: version: 1.0.4, author: OneTrust, Llc, Auto-updates disabled
Header and Footer Scripts: version: 2.2.1, author: Digital Liberation, Auto-updates disabled
WP Engine Smart Plugin Manager: version: 5.17.30, author: WP Engine, Auto-updates disabled
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Auto-updates disabled
Yoast SEO: version: 21.5, author: Team Yoast (latest version: 21.8), Auto-updates disabled

### wp-plugins-inactive (2) ###

Legacy custom Blocks: version: 1.0.0, author: Custom, Auto-updates disabled
miniOrange SSO using SAML 2.0: version: 5.0.8, author: miniOrange (latest version: 5.1.2), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1809
imagemagick_version: ImageMagick 7.1.1-15 Q16 x86_64 98eceff6a:20230729 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 128 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 7872
	imagick::RESOURCETYPE_MAP: 64 GB
	imagick::RESOURCETYPE_MEMORY: 32 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVS, BAYER, BAYERA, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FITS, FL32, FLV, FRACTAL, FTS, FTXT, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, JXL, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MPO, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, QOI, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, STRIMG, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X3F, XBM, XC, XCF, XPM, XPS, XV, YAML, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: 9.56.1

### wp-server ###

server_architecture: Darwin 23.1.0 x86_64
httpd_software: nginx/1.16.0
php_version: 8.1.23 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 8.1.2 (SecureTransport) LibreSSL/3.3.6
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false
current: 2024-01-16T12:52:58+00:00
utc-time: Tuesday, 16-Jan-24 12:52:58 UTC
server-time: 2024-01-16T12:52:55+00:00

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 8.1.23
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
Hey @Jorgu5 👋

Thank you for submitting this Issue here. Sadly, this is a known issue when having to extend static blocks. As soon as you start using the `inlineStyleGenerator` you are messing with the markup that gets saved by a block. So this will cause the error for any previously created instances of the block if you are not setting the default value of your new attributes in a way where they don't produce output by default. 

This is not the case if you only rely on the `classNameGenerator`. 

For most instances where you need to modify the markup with more than `classNames` the recommended approach today is using the `render_block` hook in PHP and using the `WP_HTML_Tag_Processor` to add your custom attributes dynamically. 

Because this issue is not something we can do anything about on an API level I am going to close this issue here for now. Thanks again for reporting it!

**Comment by Jorgu5** [comment]
Got it! Thank you for a prompt response :)

**Comment by Jorgu5** [comment]
Though the same happens when i'm using only `classNameGenerator` without `inlineStyleGenerator` as you can see on the screenshot, the classname from retrieved post body is not generated correctly either.  @fabiankaegy

**Comment by fabiankaegy** [comment]
@Jorgu5 Sorry, I should have been more precise about it. With the `inlineStyleGenerator` it can actually cause the block to completely fail and show the deprecation error where you need to manually click the attempt recovery button. 

With the `classNameGenerator` it is more graceful. The console still shows the issue but it will never cause the block to fail in any way. Which is because classNames already are a core attribute of any block that can be manipulated under the advanced panel in the inspector.
