### ISSUE TITLE
Migrate away from `defaultProps`

### ISSUE THREAD

**Issue by fabiankaegy** [10up/block-components#314]
prop types / `defaultProps` were deprecated all the way in 2017 and are now getting removed in React 19. 

WordPress will likely update it's React version relatively soon after the release so we should ensure we are finally finishing the migration away from `defaultProps`

https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis

**Comment by 001123** [comment]
is any tool for migrate defaultProps ?
