### ISSUE TITLE
ContentPicker: drag handle size can be inconsistent and is frequently too small

### ISSUE THREAD

**Issue by johnwatkins0** [10up/block-components#33]
**Describe the bug**

When using the ContentPicker with sortable items, the drag handle is sometimes different sizes. Sometimes it's too small to grab with the cursor.

<img width="249" alt="Screen Shot 2021-06-11 at 3 31 48 PM" src="https://user-images.githubusercontent.com/9020968/121745698-54cf2c00-caca-11eb-995a-6eb87bad47ed.png">

**Expected behavior**
The drag handle should be consistently sized **and large enough to meet accessibility standards** for interactive elements.

**Screenshots**
See above

**Additional context**

Screenshot is of the ContentPicker used in InspectorControls.

**Comment by fabiankaegy** [comment]
Should now be ressolved because of #42
