### ISSUE TITLE
ContentPicker sometimes doesn't display all saved items

### ISSUE THREAD

**Issue by laroccaf** [10up/block-components#335]
### Describe the bug

After saving some items to the content picker, when I return to the post edit page, sometimes some of the items are missing. If I reload the page, the items will appear as expected, so they are being written to the database. If editing another section on the page, it's easy to overlook that the items were removed, then saving the post results in the those items actually being removed in the database and frontend, which is a pretty big issue (I'm using it on a team section).

### Steps to Reproduce

Unfortunately, I haven't figured out how to reproduce it reliably, but it happens rather often for me, and it's accompanied by a 504 error in the console, showing what seem to be the related content items that are missing. It's happening on a staging version of WordPress on WP Engine.

### Screenshots, screen recording, code snippet

Console errors, these are probably the missing relational items:
<img width="650" alt="Screenshot 2024-07-02 at 12 08 58 PM" src="https://github.com/10up/block-components/assets/989589/11aea870-2a93-4e3b-9c96-da141da89c9b">

Here's my implementation in the edit.jsx file of a custom Gutenberg block:
```
import { __ } from '@wordpress/i18n';
import { useBlockProps } from '@wordpress/block-editor';
import { RichText } from '@wordpress/block-editor';
import { ContentPicker } from '@10up/block-components';

export default function Edit({ attributes, setAttributes }) {
	const { heading, teamMembers } = attributes;

  return (
    <div { ...useBlockProps() }>
      <RichText
        tagName="h2"
        className="heading"
        value={ heading }
        onChange={ ( value ) => setAttributes( { heading: value } ) }
        placeholder={ __( 'Heading…' ) }
      />
      <ContentPicker
        label="Select team members"
        contentTypes={['team']}
        maxContentItems={100}
        isOrderable={true}
        content={teamMembers}
        onPickChange={(newPosts) => setAttributes({ teamMembers: newPosts })}
      />
    </div>
  );
}
```

### Environment information

- Device: iMac 2017, MacOS 13.6.3
- Browser: Chrome 126

### WordPress information

WordPress 6.5.5
Block Components: 1.19.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
Hey @laroccaf 👋 

Can you share your `block.json` file please? 

I want to check something about how the `teamMembers` attribute is defined

**Comment by laroccaf** [comment]
Sure @fabiankaegy, here it is:
```
{
	"$schema": "https://schemas.wp.org/trunk/block.json",
	"apiVersion": 3,
	"name": "fl/team",
	"version": "0.1.0",
	"title": "Team",
	"category": "widgets",
	"icon": "groups",
	"description": "Team grid with bio popup window.",
	"example": {},
	"attributes": {
		"heading": {
			"type": "string",
			"source": "html",
			"selector": ".heading"
		},
		"teamMembers": {
			"type": "array",
			"default": []
		}
	},
	"supports": {
		"html": false,
		"anchor": true
	},
	"textdomain": "fl",
	"editorScript": "file:./index.js",
	"editorStyle": "file:./index.css",
	"style": "file:./style-index.css"
}
```
