### ISSUE TITLE
Content Picker: Paginate results or use Load More button; Avoid inifinte scroll.

### ISSUE THREAD

**Issue by claytoncollie** [10up/block-components#51]
**Is your enhancement related to a problem? Please describe.**
The content picker results modal should follow WordPress' existing patterns such as pagination or a load more button. 

**Describe the solution you'd like**
Pagination would show 10 or a configurable number of results upon search then paginate accordingly. Or search results should follow the new Media Library design pattern that displays a `Load More` button for the visitor to initiate the next set of results. In both cases, infinite scroll should be avoided due to accessibility limitations summarized in this [post](https://core.trac.wordpress.org/ticket/40330)

**Comment by tlovett1** [comment]
Agreed, this would be a great improvement.

**Comment by tlovett1** [comment]
FYI this is being worked on by @xavortm
