### ISSUE TITLE
Add: `ColorSettings` Component

### ISSUE THREAD

**Issue by fabiankaegy** [10up/block-components#68]
Core comes with either a `PanelColorSettings` or a `ColorPalette` component. There are many use cases though where we don't want to have the Color Settings in their own Inspector Panel but rather want the setting to live alongside other settings in a Panel. 

The solution here would be a custom component called `ColorSettings` which can accept a label etc. 

It can essentially be built using the `BaseControl` from `@wordpress/components`.

**Comment by arcadioramos** [comment]
There's a way to know how to run the development project to try to start developing this component?

**Comment by xavortm** [comment]
Hey @arcadioramos , you can check out is the contributing notes added here: https://github.com/10up/block-components/blob/develop/CONTRIBUTING.md#working-on-a-new-or-existing-component under **Working on a new or existing component** on setting up and working on a new patch 👍

**Comment by fabiankaegy** [comment]
@ajmaurya99 Like discussed in our call, the idea here is to create a new Component called `ColorSettings` that uses the [`ColorPalette`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/color-palette), [`BaseControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/base-control) and [`useInstanceId`](https://github.com/WordPress/gutenberg/tree/trunk/packages/compose/src/hooks/use-instance-id) core components to build a new component.

This new component should accept all the props from both the `BaseControl` and `ColorPalette` and expose them to the end user.

**Comment by fabiankaegy** [comment]
@ajmaurya99 Essentially what I am thinking for this component is something like this: 

```js

export function ColorSetting(props) {

    const instanceId = useInstanceId( ColorSetting );

    return (
        <BaseControl {... some of the parent props}  id={instanceId} >
            <ColorPalette  {... some of the parent props} id={instanceId} />
        </BaseControl>
    );

}

```
