### ISSUE TITLE
ContentPicker: Maximum update depth exceeded

### ISSUE THREAD

**Issue by huubl** [10up/block-components#99]
### Describe your question

Hi,

I try to use the Content Picker component to make a featured pages block. But I get an error:

`Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`

I've made a repository with my code: https://github.com/huubl/featured-pages-plugin

I tried the [example block](https://github.com/10up/block-components/blob/develop/example/src/blocks/hello-world/index.js) too. But it doesn't set the `selectedPost` attribute somehow.

Building blocks and React is new to me and I can't find what I'm doing wrong. Can you point me in the right direction?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@huubl The patch for this was just merged. You can test the update already by installing the `@next` version of the block components by running `npm install --save 10up/block-components@next`. We'll be releasing a patch for it in the coming days.

**Comment by huubl** [comment]
@fabiankaegy Thanks, it's working as expected now!
